# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

#sites:
#  - name: Google
#    url: https://www.google.com
#  - name: Wikipedia
#    url: https://en.wikipedia.org
#  - name: Hacker News
#    url: https://news.ycombinator.com
#  - name: Test Broken Site
#    url: https://thissitedoesnotexist.koj.co
#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

# GitHub Pagesで公開するステータスサイトの名前
status-website:
  cname: "" # 独自ドメインを使わない場合は空欄
  baseUrl: /uptime-monitor # リポジトリ名と同じにする（例: repository名が status なら /status）
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/icon.svg
  name: My Website Status
  introTitle: サービス稼働状況
  introMessage: 私たちのウェブサイトのリアルタイム監視状況です。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# 監視するサイトのリスト
sites:
  - name: linkhola公式サイト
    url: https://www.linkhola.com/
    method: GET # 通常はGET。POSTなども可
    expectedStatusCodes:
      - 200 # 200以外をダウンとみなす
    #icon: https://www.google.com/favicon.ico

  - name: CO2計算シミュレーション
    url: https://linkhola-carbon.com

  - name: EARTHSTORY LP
    url: https://earthstory.jp/

  - name: EARTHSTORYクレジット申請
    url: https://portal.earthstory.jp/login

  - name: EARTHSTORY MP
    url: https://match.earthstory.jp/

  - name: こつこつLP
    url: https://co2co2.jp/

  - name: こつこつ管理画面
    url: https://biz.earthstory.jp
    
  - name: こつこつ自治体
    url: https://gift.earthstory.jp

  - name: こつこつWeb
    url: https://co2co2me.earthstory.jp/
    
  - name: たたたん
    url: https://tatatan.jp/
    
  - name: たたたん(base)
    url: https://tatatan.base.ec/

  - name: 通知テスト
    url: https://aaaiii.jp/

# 監視の間隔（重要）
# 毎日 UTC 21:00 (= 日本時間 翌06:00) に実行
schedule: "0 21 * * *"
